# Generated by Django 5.2.10 on 2026-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, editable=False, max_length=7),
        ),
    ]
